### ISSUE TITLE
ADD: Pools / Liquidity - Volume/APR

### ISSUE THREAD

**Issue by xBi0** [weweswap/app-page#101]
Visit Figma:
https://www.figma.com/design/CwiuShU0mwYammHrR1Hv4x/WEWESWAP-WEWE?node-id=5600-15327&node-type=frame&t=BJL6BvdWEgN3vaQM-0

ADD:
- [x] TVL ( total position of the vault in the uniV4 pool )
- [x] RANGE ( infinity range)
- [x] VOLUME ( needs Subgraph )
- [x] APR ( needs Backend )

Confirm:

- [x] Size and Fonts

![image](https://github.com/user-attachments/assets/aba5a47e-6e40-4cdd-a7a1-47e6bb9e1766)

**Comment by hippocampus-web3** [comment]
Depends on https://github.com/weweswap/app-page/issues/104
