### ISSUE TITLE
Fix- Pools/ liquidity/deposit - APR/TVL

### ISSUE THREAD

**Issue by xBi0** [weweswap/app-page#103]
Visit Figma:
https://www.figma.com/design/CwiuShU0mwYammHrR1Hv4x/WEWESWAP-WEWE?node-id=5600-15327&node-type=frame&t=BJL6BvdWEgN3vaQM-0

1- ADD
- [x] APR ( needs Backend )

2- ADD:
- [x]  TVL ( total position of the vault in the uniV4 pool )
- [x]  Incentives( Future Masterchef ignore for now)
- [x]  VOLUME ( needs Subgraph )
- [x]  Fees/day ( needs Backend )

3- ADD:
- [x] Users BalanceOf WEWE and USDC

 
 
![image](https://github.com/user-attachments/assets/0680a1e8-18ed-4aff-9670-753762a2540a)

**Comment by masterjacy01** [comment]
@mmrz this still needs the volume
