### ISSUE TITLE
Fix- Pools/ liquidity/deposit - Confirmations cards - During deposit flow

### ISSUE THREAD

**Issue by xBi0** [weweswap/app-page#105]
Visit Figma:
https://www.figma.com/design/CwiuShU0mwYammHrR1Hv4x/WEWESWAP-WEWE?node-id=4123-441867&node-type=frame&t=BJL6BvdWEgN3vaQM-0

1- Check fix:
- [x] Metamask Warning on deposit

2- fix:
 - [x] Deposit Confirmation cards Text is wrong - check figma " Please Deposit Tokens "
![image](https://github.com/user-attachments/assets/baf0df18-ade9-4c5b-858c-9ab458295dbc)

**Comment by hippocampus-web3** [comment]
The warning is reported to Blockaid as false positive because we already has been verified the contract https://basescan.org/address/0x6bAffADA267Ef0FbdDEFc05592271bED9a0B4a5E
