### ISSUE TITLE
ADD- Pools/ My Shares/

### ISSUE THREAD

**Issue by xBi0** [weweswap/app-page#106]
Visit Figma:
https://www.figma.com/design/CwiuShU0mwYammHrR1Hv4x/WEWESWAP-WEWE?node-id=4123-441867&node-type=frame&t=BJL6BvdWEgN3vaQM-0

1 ADD:

- [x]  Shares
- [x]  APR
- [x]  pending rewards
- [x] total value of users shares in $
- [x] Claim fees
- [x] manage connected

![image](https://github.com/user-attachments/assets/ebb837c4-7bfc-455f-acf3-cf1393dcffcb)

**Comment by hippocampus-web3** [comment]
Last change related with this on this https://github.com/weweswap/app-page/pull/118
