### ISSUE TITLE
Add - POOL - Shares balance in tokens

### ISSUE THREAD

**Issue by xBi0** [weweswap/app-page#175]
Based on user review
![image](https://github.com/user-attachments/assets/ba5be726-2c1e-4bbd-a971-b8e79cf797e3)

Add amount of token that shares represent
![image](https://github.com/user-attachments/assets/7e326174-e54f-4e91-8974-8f3948e52938)
https://www.figma.com/design/CwiuShU0mwYammHrR1Hv4x/WEWESWAP-WEWE?node-id=4123-443789&node-type=frame&t=ov9LE5w5wmGNhWbj-0

**Comment by Rohan749** [comment]
Merged: https://github.com/weweswap/app-page/pull/240
