### ISSUE TITLE
FRONT END - improvements

### ISSUE THREAD

**Issue by xBi0** [weweswap/app-page#184]
- [x] give result in token units
- [x] add a small extra text with 80% transparency with dollar value

![image](https://github.com/user-attachments/assets/602851a8-a862-448e-a4b6-fab78bef90d1)

**Comment by Rohan749** [comment]
Moving forward with this expected structure
![Screenshot 2024-10-16 at 12 16 17 PM](https://github.com/user-attachments/assets/9567bb0d-3d6e-4832-9d47-1f0db26f702d)

**Comment by Rohan749** [comment]
Fix: https://github.com/weweswap/app-page/pull/187
