### ISSUE TITLE
Fix - Swap input UX issue

### ISSUE THREAD

**Issue by mmrz** [weweswap/app-page#196]
<img width="817" alt="Screenshot 2024-10-21 at 12 03 49" src="https://github.com/user-attachments/assets/749e0d6b-8afa-4f77-a6fa-cb6ea16a3df5">

**Comment by Rohan749** [comment]
Details about the issue:
- estimates didn't load
- estimates showed for eth when i had wewe selected
- invert tokens arrow changes tokens
- took like 10 refreshes to finally get it
