### ISSUE TITLE
Pool Deposit - WEWE amount doesn't change with buttons & slider

### ISSUE THREAD

**Issue by randomiserr** [weweswap/app-page#239]
When depositing into the WEWE/USDC pool, the WEWE amount is stuck at 0.0000 when you try to use the slider or the buttons.

The WEWE amount changes only when you manually adjust the USDC or WEWE

<img width="772" alt="image" src="https://github.com/user-attachments/assets/a571b650-f012-446e-96de-a5e56b467835">

**Comment by Rohan749** [comment]
Working without any bugs for now.
