### ISSUE TITLE
add zap-out feature

### ISSUE THREAD

**Issue by masterjacy01** [weweswap/app-page#244]
Basically the same as zap-in, only the other way around. 
So user starts with shares and gets 1 asset in the end. He has to select which one.

Still need to check which input will be even needed for the SC interation for zap-out. But API will give you all you need. 
Probably sync with @masterjacy01 along the way is necessary for the details. Starting with the UI might be good

**Comment by Rohan749** [comment]
Added zap out feature and changes made in FE according to figma. Currently under review: https://github.com/weweswap/app-page/pull/256

**Comment by Rohan749** [comment]
Merged
