### ISSUE TITLE
Add ZAPs explainer

### ISSUE THREAD

**Issue by randomiserr** [weweswap/app-page#249]
Deposit in the pool with a single token. Half of your deposit will be automatically sold for the other asset in the pool ratio.

https://www.figma.com/design/CwiuShU0mwYammHrR1Hv4x/WEWESWAP-WEWE?node-id=4990-49491&t=B4uNVxBebakvOGic-1

![Image](https://github.com/user-attachments/assets/8a7d8139-6bc6-40b0-9dfd-fa453afe0a8c)

**Comment by Rohan749** [comment]
Changes made according to figma in the FE. Currently under review. PR: https://github.com/weweswap/app-page/pull/256
