### ISSUE TITLE
Merger - Add Caps progress bar

### ISSUE THREAD

**Issue by randomiserr** [weweswap/app-page#252]
https://www.figma.com/design/CwiuShU0mwYammHrR1Hv4x/WEWESWAP-WEWE?node-id=4995-49696&t=nPnIJE7WtFXd7Wtz-1

Merger caps progress bar. The progress should be calculated from the WEWE maxSupply/ Total Vested WEWE

<img width="311" alt="image" src="https://github.com/user-attachments/assets/69e38c47-7f59-4e33-9bd1-ed143f6f9dec">

**Comment by bitcoinbrisbane** [comment]
This is nice!
